### ISSUE TITLE
Bolt Ring does not work

### ISSUE THREAD

**Issue by TaprootFreak** [DFXswiss/btc-wallet#100]
For some reason, our solution does not work with the product from https://bitcoin-ring.com

**Comment by TaprootFreak** [comment]
I have done various tests but have not yet found a solution.

I checked my NFC ring and my NTAG 424 with the BoltCard app and found no difference.

https://play.google.com/store/apps/details?id=com.lightningnfcapp&hl=de_CH

When I program my Bolt Ring, I always have the following phenomenon.

- The process aborts during programming
- no error message is visible 
- then the Bolt Ring is programmed, it looks exactly the same as another card.
- the Bolt Ring does not work for payments
- it can be reset

**Comment by Danswar** [comment]
Pause until we can coordinate with backend team on how to solve this problem:

![telegram-cloud-photo-size-4-6039671986633951114-y](https://github.com/DFXswiss/btc-wallet/assets/48102227/44cb4d8b-2c92-4737-9c8d-7769f9eff1f4)

**Comment by TaprootFreak** [comment]
With the current version, it is very unlikely that a real user will register a UID twice. I therefore consider this problem to be solved at present.
