### ISSUE TITLE
lds links are not correct

### ISSUE THREAD

**Issue by TaprootFreak** [DFXswiss/btc-wallet#101]
![image](https://github.com/DFXswiss/btc-wallet/assets/142087526/ce899cce-ab3c-44d3-87df-73268716f4c0)

**Comment by TaprootFreak** [comment]
![image](https://github.com/DFXswiss/btc-wallet/assets/142087526/6007bd17-8720-4efd-9a11-6f85f11c39de)

**Comment by TaprootFreak** [comment]
Normal transactions work correctly.

But the refund link does not seem to be set correctly yet.

**Comment by Danswar** [comment]
**New description:**

Pay Card (refund address lnurl://LNURL1DP68GURN8GHJ7ER9WCHXC6T8DP6XU6TWVUH8XURPVDJJ7A339A3X7MR5VDSHYERN9AKXUATJD3CZ7CJ9X34KZNFJFFURXU6HVA2KZKZEXDAYSS6KEUMS3H)

![Screenshot 2024-06-25 at 10 01 17 AM](https://github.com/DFXswiss/btc-wallet/assets/48102227/93c93a65-d0e1-478f-9196-e8c4058b6010)


Also the response of that link has another callback url that has been fixed

<img width="731" alt="Screenshot 2024-06-25 at 10 02 27 AM" src="https://github.com/DFXswiss/btc-wallet/assets/48102227/d11b1731-5671-4f2b-9ce5-4d82456e51f3">


@TaprootFreak

**Comment by TaprootFreak** [comment]
cool ! 😎
