### ISSUE TITLE
LNURLP  Questions

### ISSUE THREAD

**Issue by TaprootFreak** [DFXswiss/btc-wallet#109]
Which symbols are permitted for an LNURLP link? 

What is the maximum length of a link?

**Comment by Danswar** [comment]
**What is the maximum length of a link?**

The LNURL specification does not apply limits to the length of the link. I would dare to say that the longest you could find in the wild are around 1024 characters but the ones generated by our app seems to be fixed to 126 characters.

**Which symbols are permitted for an LNURLP link?**

If by symbols you mean the characters in the LNURL, then that is an string Bech32 encoded so you will only find:
**LNURL1** + { any combination of **023456789acdefghjklmnpqrstuvwxyz** }.  In other words no 1, i, b, an other prone to confusion characters. 

In the other hand, if by symbol you meant currency symbol, it seems that the LNURL can point to any of the 4 wallet (BTC, EUR, USD, CHF) but unsure how that works for the non-btc ones.

@TaprootFreak
