### ISSUE TITLE
Übersetzung im Sende-Screen und bei manueller Adresseingabe fehlt

### ISSUE THREAD

**Issue by Wendel-BS** [DFXswiss/btc-wallet#134]
**Status:**
Wenn die Spracheinstellung in der App auf eine bestimmte Sprache eingestellt ist, 
wird davon ausgegangen, dass die App mit dem Nutzer in der entsprechenden Sprache (z.B. deutsch) kommuniziert.

**Problem:**
Wenn man hinten auf ‚Senden‘ geht, dann ‚spricht‘ die App mit mit dem Nutzer im Senden-Screen englisch, 
selbst wenn sie auf deutsch eingestellt ist.

Wenn man dann im ‚Senden Screen‘ auf das Tastatur-Icon drückt (wo der blaue Pfeil hin zeigt), 
dann ‚spricht‘ die App bei der manuellen Adresseingabe weiterhin englisch  (Screenshot 2).

**Screenshots :**
<img width="962" alt="image" src="https://github.com/user-attachments/assets/11c9e3a9-16f3-4997-82b9-2013c86a57fb">

<img width="521" alt="image" src="https://github.com/user-attachments/assets/c16da4c5-8819-4cef-9185-bdcb4b026f29">

<img width="761" alt="image" src="https://github.com/user-attachments/assets/3d8c4ee7-347d-41c3-a085-4a0e88d5aabe">

**Erwartungshaltung:**
▫️ Einheitliche Sprache in allen Screens gemäß der Voreinstellung
▫️ Nutzererlebnis verbessern
▫️ Optimierung (Verbesserung) der App

**Comment by Danswar** [comment]
**Übersetzte Nachricht** 

Leider konnte ich in diesem Fall nicht allzu viel tun, denn wir brauchen Hilfe bei den Übersetzungen, da sie in zu vielen Sprachen vorliegen. Können wir in Erwägung ziehen, für einen Übersetzungsdienst zu bezahlen? Ich kann nach einigen Optionen suchen und sie Ihnen vorlegen.

**Original Message:**

Unfortunately I couldn't  do too much for this one, we need help with the translations as they are too many in too many languages. Can we consider to pay for a translation service? I can look for some options and present them to you.

**Comment by TaprootFreak** [comment]
@davidleomay

**Comment by Danswar** [comment]
strings are included in this PR #138

**Comment by davidleomay** [comment]
> @davidleomay

@TaprootFreak bisher haben wir nur in die gängigen DFX-Sprachen (EN, DE, ES, FR, IT, PT) übersetzt. Passt das weiterhin so?
