### ISSUE TITLE
Offramp - falsche Angaben zum Mindestauszahlungsbetrag

### ISSUE THREAD

**Issue by Wendel-BS** [DFXswiss/btc-wallet#3]
**Status:**
Auf der Payment-Seite zu den Wallet-Adressen werden in der Sellroute (bei der Offramp Deposit Adresse) der Mindestauszahlungsbetrag angezeigt.

**Problem:**
Der angezeigte Mindestauszahlungsbetrag (laut dem hier gezeigten Screenshot) liegt bei 1 Euro bzw 1 Dollar bzw 1 CHF.

Bei nativen Bitcoin sollte es jedoch der zehnfache der o.g Fiat-Werte sein, 
oder 0.0005 BTC.

Falsche Angaben bei den Routen Details führen dazu, dass Nutzer der App evtl. unterhalb dem Mindestauszahlungsbetrag BTC-Anteile übertragen und dann der Auszahlungsbetrag von DFX nicht weiter verarbeitet wird.

**Screenshot:**

![BTC-Offramp](https://user-images.githubusercontent.com/117222124/212682059-383383a0-da1d-4c6d-93d2-8a2e8242fe16.jpg)

**Erwartungshaltung:**

Angabe des Mindestauszahlungsbetrags: 0.0005 BTC

**Comment by Kolibri1990** [comment]
Fixed
