### ISSUE TITLE
EURO und CHF Bitcoin-Kurs in der App nicht korrekt

### ISSUE THREAD

**Issue by Wendel-BS** [DFXswiss/btc-wallet#31]
**Status:**
Über _Setting —> Währung_ stellt man in der App die Anzeige seiner BTC-Anteile in der Wunschwährung ein.
Unten am Fenster wird die Quelle, bzw. CEX benannt, 
sowie der entsprechende Bitcoin-Kurs in der eingestellten Fiat-Währung, 
ferner der Zeitpunkt, wann der Kurs zuletzt aktuallisiert wurde.

**Problem**:
👉  In der DFX Community wurde reklamiert, dass es bei der eingestellten Fiatwährung EUR und / oder CHF zu signifikanten Abweichungen zum tatsächlichen BTC-Kurs kommt, wohin gegen der BTC-Kurs in US-Dollar passt.
(der Kursunterschied in EUR liegt bei rund 2000 € --> siehe die beigefügten Screen-Shots)

👉  Die relevante CEX für den BTC-Kurs bei DFX ist Kraken.
In der DFX BTC only App stammen die Preisangaben jedoch von CoinDesk.
Bei der BlueWallet stammen die Preisangaben hingegen von Bitstamp.

**Ursachenforschung**:
Es ist zu ermitteln, 
▫️ warum die App bei EUR und CHF Kurse anzeigt, welche nicht dem aktuellen BTC-Kurs entsprechen.
▫️ ob auch andere Fiat-Währungen in der App nicht korrekt angezeigt werden.
▫️ ob anstatt der angezeigten CEX „Coindesk“ nicht lieber die für DFX relevante CEX „Kraken“ angezeigt werden kann.

 **langfristige Abstellmaßnahme**:
👉  Sobald die Grundursache für den Fehler des falschen Kurses gefunden ist, ist dieser zu beseitigen und sicherzustellen, dass zukünftig der korrekte Kurs in der entsprechenden Fiat-Währung angezeigt wird.

👉  Die Preisangaben des BTC-Kurses sollten nach Möglichkeit von Kraken angezeigt werden, also der für DFX relevanten CEX.

**Screenshots:**

- Screen-Shot aus der DFX BTC only App mit falschem EURO-Kurs für den Bitcoin:
![telegram-cloud-photo-size-2-5332481573825662544-x](https://github.com/DFXswiss/btc-wallet/assets/117222124/e165bde5-3bd2-411d-bd72-5a3924ad7e75)

- Smartphone Screen-Shot mit aktuellem EURO-Kurs für den Bitcoin:
![telegram-cloud-photo-size-2-5332481573825662545-y](https://github.com/DFXswiss/btc-wallet/assets/117222124/d75525c4-4e9c-4259-9664-dd0a908f0e38)

- Screen-Shot aus der BlueWallet mit aktuellem EURO-Kurs für den Bitcoin:
![telegram-cloud-photo-size-2-5332481573825662553-y](https://github.com/DFXswiss/btc-wallet/assets/117222124/e83ffd95-4a60-4a86-b164-0ae015d17197)

**Gegenüberstellung einer Transaktion in zwei BTC-Apps**:

Auswirkungen des falsch angezeigten Kurses auf eine zurückliegende Transaktion im Vergleich zwischen 
▫️der DFX BTC only App 
▫️der BlueWallet.
(Die Screen-Shots wurden zur gleichen Zeit erstellt.)

- Hier der Screen-Shot mit dem Wert aus der DFX BTC only App:
![telegram-cloud-photo-size-2-5334975236132686120-y](https://github.com/DFXswiss/btc-wallet/assets/117222124/32d5d5b3-bffc-487e-bef7-fb8665e4a1b6)

- Hier der Screen-Shot mit dem Wert aus der BlueWallet:
![telegram-cloud-photo-size-2-5334975236132686121-y](https://github.com/DFXswiss/btc-wallet/assets/117222124/4e2cf71a-9d2d-4c04-b68a-4ef4fd0aafe9)

- Hier die Berechnung der Abweichung zwischen den beiden Wertangaben der selben Transaktion:
![telegram-cloud-photo-size-2-5334975236132686119-y](https://github.com/DFXswiss/btc-wallet/assets/117222124/66e65f3f-ba98-44d6-a26d-102b2d789e6f)

**Kommentar**:

> In Dollar ist es richtig. CHF und EUR sind total falsch.

**Quelle**:
https://t.me/DFXswiss/98939

**Erwartungshaltung**:
▫️ Beseitigen des Kursanzeigefehlers
▫️ Nutzererlebnis verbessern
▫️ Optimierung (Verbesserung) der App

**Comment by Kolibri1990** [comment]
Implemented in new BTC Taro Wallet
