### ISSUE TITLE
Adressbuch für die DFX BTC Taro (und die Frankencoin ?) App

### ISSUE THREAD

**Issue by Wendel-BS** [DFXswiss/btc-wallet#37]
**Status**:
Im Gegensatz zur (obsoleten) DFX Defichain App verfügen die beiden aktuellen DFX Apps
▫️ BTC Taro
▫️ (FrankenCoin)
leider (bisher) nicht über ein Adressbuch.

**Problem**:
Beim Versenden von Coins an eine öfters benötigte Wallet-Addresse, muss man diese immer zunächst erst raussuchen, kopieren und es ist immer darauf zu achten, dass die verwendete Wallet-Adresse auch wirklich passt.
(vermeidbarer Mehraufwand)

Bei Verwendung des Addressbuches wäre dieser (Mehr-)Aufwand nur einmal beim Eintragen der Wallet-Adresse ins Adressbuch erforderlich.

**Quelle**:
DFX Community
Beitrag:   https://t.me/DFXswiss/100641

**Nutzer-Kommentar:**

> Ich fände es schon sehr charmant, 
> wenn es in der BTC BTC Taro APP ein Adressbuch 
> wie in der DFX Defichain APP geben würde.

**Screen-Shot**:

![IMAGE 2024-04-21 18:15:38](https://github.com/DFXswiss/btc-wallet/assets/117222124/df0436a8-2900-4c10-a426-6f7b17984592)
Neuer Adressbucheintrag - Bild 1

![IMAGE 2024-04-21 18:16:40](https://github.com/DFXswiss/btc-wallet/assets/117222124/e219bd83-d4ed-437d-964d-fc24ddec68a9)
Neuer Adressbucheintrag - Bild 2

**Erwartungshaltung:**
▫️ Nutzerlebnis verbessern
▫️ Optimierung (Verbesserung) der App(s)
▫️ Bedienung beim Versenden von Coins erleichtern

**Comment by TaprootFreak** [comment]
Ja soll es in Zukunft geben, ist aber momentan noch nicht Prio.
