### ISSUE TITLE
Remove BugSnag

### ISSUE THREAD

**Issue by davidleomay** [DFXswiss/btc-wallet#46]
Remove BugSnag from code and build files

**Comment by TaprootFreak** [comment]
I used https://obdev.at/products/littlesnitch/index.html to investigate the behaviour of our wallet. I realised that many servers are being accessed in the background. 

<img width="332" alt="Bildschirmfoto 2024-05-13 um 14 10 29" src="https://github.com/DFXswiss/btc-wallet/assets/142087526/13e18846-cfd8-49d7-9247-c56e70689110">

Why are all these servers targeted?

Can we remove these external services from our wallet?

Our wallet should address as few external services as possible. We are not interested in tracking and the like.

**Comment by Danswar** [comment]
> Why are all these servers targeted?
> 
> Can we remove these external services from our wallet?
> 
> Our wallet should address as few external services as possible. We are not interested in tracking and the like.

@TaprootFreak I checked the list of server in the screenshot and there are only 2 externals services:
- Coingecko: used for quotation.
- Bugsnag: bug reporting, it's been removed in #60

All others are peer nodes that the instance of Electrum in the wallet can connect to, so they are not analytics or similars. You can check out the complete list here in the code:

https://github.com/DFXswiss/btc-wallet/blob/48a7ca6831d471543d2bea1b2fd0363f68aa254f/blue_modules/BlueElectrum.js#L51

I would say those are OK, but let me know if you want me to replace them for other nodes that you run or trust.

**Comment by TaprootFreak** [comment]
Ok, thank you
That's good to know!
