### ISSUE TITLE
Alert overflow when server does not respond

### ISSUE THREAD

**Issue by Danswar** [DFXswiss/btc-wallet#58]
The modal show up so many times that makes the wallet unusable.

https://github.com/DFXswiss/btc-wallet/assets/48102227/0988bf8f-f011-4b29-8bae-94d00fecb9d2

**Comment by TaprootFreak** [comment]
Yes, this should be fixed.

The error should only be displayed at the bottom and no popup should open.

**Comment by TaprootFreak** [comment]
Ok I see
Yes, I don't think we need to take any further steps here and can currently consider this to be closed. 
@Danswar
