### ISSUE TITLE
Remove manual syncing

### ISSUE THREAD

**Issue by TaprootFreak** [DFXswiss/btc-wallet#63]
When I open a specific wallet, I can synchronise the wallet manually by dragging my finger downwards. 

<img width="350" alt="Bildschirmfoto 2024-05-17 um 22 09 42" src="https://github.com/DFXswiss/btc-wallet/assets/142087526/238ab5d1-6e52-4780-8d5b-9dd17b1b85ba">

I think we should remove it completely. 
When I open the app, I expect the app to synchronise fully automatically in the background. For example, there should be an automatic query on the server every second. 
I don't think anyone has opened the app for fun. So when the app is open, it should be constantly synchronised without the user having to request it manually.

**Comment by TaprootFreak** [comment]
A better idea:

When the user drags down with the finger, not the spinner should be displayed but a text. 
-> last successful synchronisation {minutes / seconds ago}
That would be most useful.

**Comment by Danswar** [comment]
Unfortunately, the spinner you talk offers very little customization, you can only choose to have it or not to have it.

the API of this component only offers to have a title only  for the iOS version and to change the color of it.

So I'll wait for you decision about removing it or not.

https://reactnative.dev/docs/refreshcontrol#title-ios

https://github.com/DFXswiss/btc-wallet/assets/48102227/94e8f303-e212-405e-a669-3ebac7a1e7f1

**Comment by Danswar** [comment]
Regarding querying every one second we have a limitation. Refreshing that view is actually composed by +4 request that usually can take more than a second. I think at best we can trigger one update after the other to keep the screen as updated as possible.

Here are some logs with timings that BlueWallet's dev put in that functionality, look that some of them are near to 3 seconds. I guess a some point they tried to do the same a that could be the origin of the spinner.

![Screenshot 2024-05-20 at 2 28 29 PM](https://github.com/DFXswiss/btc-wallet/assets/48102227/e2cb15fb-8043-48d1-961d-3ccaddda8bce)

@TaprootFreak

**Comment by TaprootFreak** [comment]
Ok
Yes then we should remove the spinner and the manual update completely.

You can decide for yourself which method is the best to continuously update in the background. 

@Danswar

**Comment by Danswar** [comment]
Added to #70
