### ISSUE TITLE
front-end improvements

### ISSUE THREAD

**Issue by TaprootFreak** [DFXswiss/btc-wallet#81]
I will use this issue to document small things that are not optimal.

**Comment by TaprootFreak** [comment]
![photo_2024-06-05 17 24 26](https://github.com/DFXswiss/btc-wallet/assets/142087526/698c7b6e-1dd7-4e68-8020-7169a32ba18b)


The title, the button at the top left and the "Cancel" button at the bottom are missing on the right-hand screen

**Comment by TaprootFreak** [comment]
![photo_2024-06-05 17 25 54](https://github.com/DFXswiss/btc-wallet/assets/142087526/d13b1c7c-7a51-44de-ae76-316fd25cf105)

This screen cannot be scrolled, it is not possible to see the "Share" button

**Comment by TaprootFreak** [comment]
![photo_2024-06-08 22 32 30](https://github.com/DFXswiss/btc-wallet/assets/142087526/18bfc31a-9379-473e-9548-3264ab3b5de1)

On the main screen, there are 3 points at the top right for the menu

The menu is not displayed in the wallet itself. 
The menu button with the three dots should be displayed at the top right of all 3 wallets. When the user clicks on the 3 dots, the settings menu always opens. The same view always appears, regardless of the wallet in which the menu button is pressed.

**Comment by TaprootFreak** [comment]
Not all buttons can be used with an Iphone Mini.

For example, the Share button cannot be pressed on the Receive screen and the create MultiDevice Wallet screen does not work either.

**Comment by TaprootFreak** [comment]
![image](https://github.com/DFXswiss/btc-wallet/assets/142087526/ae06e479-99fb-4683-a33b-4e1ec020a980)

If the Iphone loses the Internet connection then no pop-up should appear.

**Comment by TaprootFreak** [comment]
![image](https://github.com/DFXswiss/btc-wallet/assets/142087526/9f4290f6-b4ba-4e3b-b74d-0375aa7ffc1b)

**Comment by Danswar** [comment]
![Screenshot 2024-06-21 at 3 35 01 PM](https://github.com/DFXswiss/btc-wallet/assets/48102227/1364c426-47dc-4be2-9c45-0483cc472afc)

**Comment by TaprootFreak** [comment]
Top
