### ISSUE TITLE
Do we need the BackUp button?

### ISSUE THREAD

**Issue by TaprootFreak** [DFXswiss/btc-wallet#98]
![image](https://github.com/DFXswiss/btc-wallet/assets/142087526/c01651d5-8498-4ee9-bcc6-3b011d5b4ca0)

![image](https://github.com/DFXswiss/btc-wallet/assets/142087526/ad73e08b-fd03-45a5-aab4-40b4835a5634)

I think the warning text is superfluous. 
What would be the best solution?

Should we simply display the back-up information in the general pay card information screen of Issue 96?

https://github.com/DFXswiss/btc-wallet/issues/96

Then we can remove the BackUp button here in the map view, right?

**Comment by Danswar** [comment]
Recommendation: Move the backup QR code to the settings screen
